spring.application.name=crmed
spring.datasource.url=jdbc:oracle:thin:@crmedgithub_high
spring.datasource.username=ADMIN
spring.datasource.password=Giovana0426$
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=/Users/jdematos/Documents/Java/Wallet_crmedgithub
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true